# Generated by Django 4.1.5 on 2023-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntradaDeBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=128)),
                ("subtitulo", models.CharField(max_length=256)),
                ("autor", models.CharField(max_length=64)),
                ("fecha_entrada", models.DateField(null=True)),
                ("cuerpo", models.TextField()),
                ("imagen", models.ImageField(upload_to="")),
            ],
        ),
    ]
