# Generated by Django 4.1.5 on 2023-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradadeblog", name="imagen", field=models.TextField(),
        ),
    ]
