# Generated by Django 4.1.5 on 2023-01-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_entradadeblog_imagen"),
    ]

    operations = [
        migrations.RemoveField(model_name="entradadeblog", name="fecha_entrada",),
        migrations.RemoveField(model_name="entradadeblog", name="imagen",),
    ]
