# Generated by Django 4.1.5 on 2023-01-28 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_entradadeblog_fecha_entrada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradadeblog",
            name="cuerpo",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
