# Generated by Django 4.1.5 on 2023-01-30 22:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_entradadeblog_cuerpo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradadeblog",
            name="cuerpo",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
