# Generated by Django 4.1.5 on 2023-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_imagenblog"),
    ]

    operations = [
        migrations.RemoveField(model_name="imagenblog", name="blog",),
        migrations.DeleteModel(name="Post",),
        migrations.AddField(
            model_name="entradadeblog",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
        migrations.DeleteModel(name="ImagenBlog",),
    ]
