# Generated by Django 4.1.5 on 2023-02-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_entradadeblog_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="entradadeblog", name="imagen",),
        migrations.AlterField(
            model_name="entradadeblog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
